#!/usr/bin/env bash
set -euo pipefail

# 定位系统盘上的源码仓库和用户指定的挂载盘。
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
MOUNT_ROOT="${1:-${MINITRAIN_MOUNT_ROOT:-/data}}"
if [[ "$MOUNT_ROOT" != /* || ! -d "$MOUNT_ROOT" ]]; then
  echo "usage: $0 /absolute/mounted/disk/path" >&2
  exit 2
fi
MOUNT_ROOT="$(realpath "$MOUNT_ROOT")"

# 防止误把系统根分区当作实验存储盘。
MOUNT_TARGET="$(findmnt -n -o TARGET -T "$MOUNT_ROOT" 2>/dev/null || true)"
if [[ -z "$MOUNT_TARGET" ]]; then
  echo "Cannot identify the filesystem containing $MOUNT_ROOT" >&2
  exit 2
fi
if [[ "$MOUNT_TARGET" == "/" && "${ALLOW_SYSTEM_DISK_STORAGE:-0}" != "1" ]]; then
  echo "$MOUNT_ROOT is on the system root filesystem; mount the data disk first" >&2
  exit 2
fi
if [[ ! -w "$MOUNT_ROOT" ]]; then
  echo "Mounted disk is not writable: $MOUNT_ROOT" >&2
  exit 2
fi

# 在挂载盘内创建实验产物、编译缓存和临时文件目录。
STORAGE_ROOT="${MINITRAIN_STORAGE_ROOT:-$MOUNT_ROOT/mini-train-sys}"
STORAGE_ROOT="$(realpath -m "$STORAGE_ROOT")"
case "$STORAGE_ROOT/" in
  "$MOUNT_ROOT/"*) ;;
  *) echo "Storage root must stay inside mounted disk: $MOUNT_ROOT" >&2; exit 2 ;;
esac
ARTIFACTS_ROOT="$STORAGE_ROOT/artifacts"
mkdir -p \
  "$ARTIFACTS_ROOT" \
  "$STORAGE_ROOT/cache/cuda_ext" \
  "$STORAGE_ROOT/cache/triton" \
  "$STORAGE_ROOT/cache/torch_extensions" \
  "$STORAGE_ROOT/cache/torch" \
  "$STORAGE_ROOT/cache/pip" \
  "$STORAGE_ROOT/cache/xdg" \
  "$STORAGE_ROOT/cache/huggingface" \
  "$STORAGE_ROOT/tmp"

# 将仓库内 artifacts 安全链接到挂载盘；已有真实目录时拒绝覆盖。
ARTIFACTS_LINK="$ROOT/artifacts"
if [[ -L "$ARTIFACTS_LINK" ]]; then
  CURRENT_TARGET="$(realpath "$ARTIFACTS_LINK")"
  if [[ "$CURRENT_TARGET" != "$ARTIFACTS_ROOT" ]]; then
    echo "Existing artifacts symlink points to $CURRENT_TARGET, expected $ARTIFACTS_ROOT" >&2
    exit 2
  fi
elif [[ -e "$ARTIFACTS_LINK" ]]; then
  echo "Existing $ARTIFACTS_LINK was not changed." >&2
  echo "Copy it to $ARTIFACTS_ROOT, archive the original, then rerun this script." >&2
  exit 2
else
  ln -s "$ARTIFACTS_ROOT" "$ARTIFACTS_LINK"
fi

# 写入可重复加载的机器本地环境文件，训练脚本会自动读取它。
ENV_FILE="$ROOT/.minitrain-storage.env"
ENV_TMP="$ENV_FILE.tmp"
{
  printf '# Generated by scripts/bash/setup_storage.sh; do not commit.\n'
  printf 'export MINITRAIN_STORAGE_ROOT=%q\n' "$STORAGE_ROOT"
  printf 'export MINITRAIN_CUDA_BUILD_ROOT=%q\n' "$STORAGE_ROOT/cache/cuda_ext"
  printf 'export TRITON_CACHE_DIR=%q\n' "$STORAGE_ROOT/cache/triton"
  printf 'export TORCH_EXTENSIONS_DIR=%q\n' "$STORAGE_ROOT/cache/torch_extensions"
  printf 'export TORCH_HOME=%q\n' "$STORAGE_ROOT/cache/torch"
  printf 'export PIP_CACHE_DIR=%q\n' "$STORAGE_ROOT/cache/pip"
  printf 'export XDG_CACHE_HOME=%q\n' "$STORAGE_ROOT/cache/xdg"
  printf 'export HF_HOME=%q\n' "$STORAGE_ROOT/cache/huggingface"
  printf 'export TMPDIR=%q\n' "$STORAGE_ROOT/tmp"
} > "$ENV_TMP"
mv "$ENV_TMP" "$ENV_FILE"

# 输出分盘结果和下一步安装命令。
df -h "$ROOT" "$STORAGE_ROOT"
echo "System disk checkout: $ROOT"
echo "Mounted experiment storage: $STORAGE_ROOT"
echo "Next: bash scripts/bash/setup_server.sh"
